app:
    resource: '@AppBundle/Controller'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
panel:
    resource: "@AppBundle/Resources/config/routing_panel.yml"
    prefix:   /panel   